version: '3.4'

services:
  impostor:
    image: aeonlucid/impostor:nightly
    container_name: impostor
    ports:
      - 22023:22023/udp
      - 22023:22000/tcp
    volumes:
      - ./config.json:/app/config.json
      - ./config_http.json:/app/config_http.json
      - ./plugins:/app/plugins
      - /usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.1:/usr/share/dotnet/shared/Microsoft.AspNetCore.App/7.0.1
      - ./privkey.der:/app/privkey.der
